#!/bin/bash
cd ~
echo ";; This code allows the line enumaration.
(setq column-number-mode t)
(global-linum-mode 1)
;; End of line enumeration

;; This code add the permissions for pair mode with (), \"\", '' and others...
(setq electric-pair-pairs
      '(
        (?\\\" . ?\\\")
        (?\\< . ?\\>)))
(electric-pair-mode 1)
;; End of electric pair mode.

;; This code add a new theme for emacs
(load-theme 'misterioso)
;; End of theme.

;; This code allows the classic flags {copy, paste, cut, etc}
(cua-mode t)
;; End of cua mode

;; This code allows a new kind of identation for C programming language
(setq c-default-style \"bsd\"
      c-basic-offset 8
      tab-width 8
      indent-tabs-mode t)
;; End of identation code

;; This code allows the highlight for {}, () and others...
(show-paren-mode 1)
;; End of highlights

;; This code allows the visual line mode
(global-visual-line-mode 1)
;; End of visual line mode.

;; I do not remember what is this xd
(require 'whitespace)
(setq whitespace-style '(face empty lines-tail trailing))
(global-whitespace-mode t)
(setq make-backup-files nil)
;; End
" >> .emacs
