#!/bin/bash
cd ~
echo "(global-linum-mode 1)
(setq column-number-mode t)
(require 'whitespace)
(setq whitespace-style '(face empty lines-tail trailing))
(global-whitespace-mode t)
(setq c-default-style \"bsd\"
      c-basic-offset 8
      tab-width 8
      indent-tabs-mode t)
(cua-mode t)
(show-paren-mode 1)
(load-theme 'misterioso)
(setq make-backup-files nil)" >> .emacs
